---
keyboard_layout: pl
locale: "en_US.UTF-8"
passwordless_sudo: false
redshift_allow_location: true
bluemann_sudo_group_nopasswd: true


geoclue_redshift_config:
  path: /etc/geoclue/geoclue.conf
  block: |
    [redshift]
    allowed=true
    system=false
    users=

polkit_blueman_rule_config:
  path: /etc/polkit-1/rules.d/51-blueman.rules
  block: "{{ lookup('file', '51-blueman.rules') }}"

firefox_config:
  path: "{{ firefox_default_profile_dir }}/user.js"
  settings:
    - key: "layout.css.devPixelsPerPx"
      value: "{{ '1.25' if hidpi else '1.00' }}"
    - key: "widget.content.gtk-theme-override"
      value: "Adwaita"

font_config:
  available_dir: /etc/fonts/conf.avail/
  enabled_dir: /etc/fonts/conf.d
  enable_files:
    - "70-no-bitmaps.conf"
    - "10-sub-pixel-rgb.conf"
    - "11-lcdfilter-default.conf"
  config_path: /etc/fonts/local.conf

xdg_config_path: "{{ ansible_env.HOME }}/.config/user-dirs.dirs"
xdg_dirs:
  download: Downloads
  music: Music
  videos: Videos
  pictures: Pictures
  documents: ''
  desktop: ''
  templates: ''
  public: ''
