
font_dir_linux: "{{ ansible_env.HOME }}/.local/share/fonts"
font_dir_mac: "{{ ansible_env.HOME }}/Library/Fonts"

font_dir: "{{ font_dir_mac if ansible_distribution == 'MacOSX' else font_dir_linux}}"

font_urls:
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/Regular/complete/Iosevka%20Nerd%20Font%20Complete.ttf"
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/Italic/complete/Iosevka%20Italic%20Nerd%20Font%20Complete.ttf"
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Iosevka/Bold/complete/Iosevka%20Bold%20Nerd%20Font%20Complete.ttf"
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Noto/Mono/complete/Noto%20Mono%20Nerd%20Font%20Complete%20Mono.ttf"
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Go-Mono/Regular/complete/Go%20Mono%20Nerd%20Font%20Complete%20Mono.ttf"
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Go-Mono/Italic/complete/Go%20Mono%20Italic%20Nerd%20Font%20Complete%20Mono.ttf"
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Go-Mono/Bold/complete/Go%20Mono%20Bold%20Nerd%20Font%20Complete%20Mono.ttf"
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Mononoki/Regular/complete/mononoki-Regular%20Nerd%20Font%20Complete.ttf"
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Mononoki/Italic/complete/mononoki%20Italic%20Nerd%20Font%20Complete.ttf"
  - "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/Mononoki/Bold/complete/mononoki%20Bold%20Nerd%20Font%20Complete.ttf"




