---
- name: configure git
  block:
    - name: install git
      package:
        name: git
        state: present
      become: "{{ true if ansible_distribution != 'MacOSX' else false }}"

    - name: set git config
      git_config:
        name: "{{ item.key }}"
        scope: global
        value: "{{ item.value }}"
      loop: "{{ git_config | dict2items }}"

    - name: put global .gitignore in place
      copy:
        src: globalgitignore
        dest: "{{ git_globalignore }}"
