---
- name: allow redshift location access
  blockinfile:
    path: "{{ geoclue_redshift_config.path }}"
    block: "{{ geoclue_redshift_config.block }}"
    backup: true
  become: true
  when: redshift_allow_location

- name: allow sudo group users to use bluemann without authentication
  blockinfile:
    path: "{{ polkit_blueman_rule_config.path }}"
    block: "{{ polkit_blueman_rule_config.block }}"
    create: true
    marker: "/* {mark} ANSIBLE MANAGED BLOCK */"
    backup: true
  become: true
  when: bluemann_sudo_group_nopasswd

- name: enable passwordless sudo
  lineinfile:
    path: /etc/sudoers
    regexp: '%sudo'
    line: "%wheel ALL = (ALL) NOPASSWD: ALL"
  become: true
  when: passwordless_sudo

- name: set locale
  block:
    - name: specify locale to generate
      lineinfile:
        path: /etc/locale.gen
        regexp: "^#{{ locale }}"
        line: "{{ locale }}"
      become: true

    - name: generate locale
      command: locale-gen
      become: true

    - name: set keyboard layout
      command: "{{ item }}"
      loop:
        - "localectl set-keymap --no-convert {{ keyboard_layout }}"
        - "localectl set-x11-keymap --no-convert {{ keyboard_layout }}"
      become: true
  when: set_locale

- name: enable virsh autocompletion for Zsh
  copy:
    src: virsh.zsh-completion
    dest: /usr/share/zsh/functions/Completion/Linux/_virsh
  become: true
  when: virtualization
