---
- name: install software
  block:
    - name: Arch-specific
      block:
        - name: make sure Vim is uninstalled (conflicts with GVim)
          pacman:
            name: vim
            state: absent
          become: true
          when: "'gvim' in pacman_packages"

        - name: install packages using Pacman
          pacman:
            name: "{{ pacman_packages | join(' ') }}"
            update_cache: true
            state: latest
          become: true

        - name: Create aur_builder user
          user:
            name: aur_builder
            group: wheel
          become: true

        - name: Allow aur_builder user
          lineinfile:
            path: /etc/sudoers.d/11-install-aur_builder
            line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
            create: yes
            validate: 'visudo -cf %s'
          become: true

        - name: install AUR helper
          aur:
            name: "{{ aur_helper }}"
            skip_installed: true
            use: makepkg
          become: true
          become_user: aur_builder

        - name: install AUR packages
          aur:
            name: "{{ item }}"
            skip_installed: true
            use: "{{ aur_helper }}"
          loop: "{{ aur_packages }}"
          become: true
          become_user: aur_builder

    - name: install Python packages
      pip:
        name: "{{ item }}"
        extra_args: --user
        state: latest
      loop: "{{ pip_packages }}"

    - name: install Vagrant plugins
      command: "vagrant plugin install {{ item }}"
      loop: "{{ vagrant_plugins }}"
      when: virtualization
  when: packages
