---
- name: install software
  block:
    - name: Arch-specific
      block:
        - name: make sure Vim is uninstalled (conflicts with GVim)
          pacman:
            name: vim
            state: absent
          become: true

        - name: install packages using Pacman
          pacman:
            name: "{{ pacman_packages | join(' ') }}"
            update_cache: true
            state: latest
          become: true

        - name: install AUR helper
          aur:
            name: "{{ aur_helper }}"
            skip_installed: true
            use: makepkg

        - name: install AUR packages
          aur:
            name: "{{ item }}"
            skip_installed: true
            use: "{{ aur_helper }}"
          loop: "{{ aur_packages }}"

    - name: install Python packages
      pip:
        name: "{{ item }}"
        extra_args: --user
        state: latest
      loop: "{{ pip_packages }}"

    - name: install Vagrant plugins
      command: "vagrant plugin install {{ item }}"
      loop: "{{ vagrant_plugins }}"
      when: virtualization
  when: packages
