---
- hosts: all
  roles:
    - role: common
      # - role: mac
      #   when: ansible_distribution == 'MacOSX'
      # - role: linux
      #   when: ansible_distribution in ['Archlinux', 'Ubuntu']
