---
- hosts: all
  vars:
    # --- set all switches to true ---
    all: false
    # --- playbook switches (alphabetical order) ---
    config: false
    fontconfig: false
    fonts: false
    git: false
    packages: false
    set_locale: false
    virtualization: false
  pre_tasks:
    - name: set all switches to true
      set_fact:
        config: true
        fontconfig: true
        fonts: true
        git: true
        packages: true
        set_locale: true
        virtualization: true
      when: all
  roles:
    - role: common
    - role: mac
      when: ansible_distribution == 'MacOSX'
    - role: linux
      when: ansible_distribution in ['Archlinux', 'Ubuntu']
